# Generated by Django 3.0 on 2020-01-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('euro', 'EUR')], default='usd', max_length=10),
        ),
    ]
