# Generated by Django 2.2.5 on 2020-01-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200113_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['-created'], 'verbose_name': 'Room Type'},
        ),
    ]
